package com.example.bricksGame.config

object LevelsConfig {

    val gameLevels: List<Level> = listOf(

        Level(
            numberLevel = 1,
            fieldGameRow = 2,
            fieldGameColumn = 2,
            additionalBrick = 2,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 0,
            bonusFillSpeed = 0.5f,
            numberOfScoreToWin = 10,
            levelMaxStep = 12
        ),
        Level(
            numberLevel = 2,
            fieldGameRow = 2,
            fieldGameColumn = 3,
            additionalBrick = 2,
            numberOfBricksToWin = 2,
            negativeBonusNumber = 0,
            bonusFillSpeed = 0.2f,
            numberOfScoreToWin = 20,
        ),
        Level(
            numberLevel = 3,
            fieldGameRow = 3,
            fieldGameColumn = 3,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 1,
            bonusFillSpeed = 0.2f,
            numberOfScoreToWin = 30,
        ),
        Level(
            numberLevel = 4,
            fieldGameRow = 3,
            fieldGameColumn = 4,
            additionalBrick = 3,
            numberOfBricksToWin = 3,
            negativeBonusNumber = 1,
            bonusFillSpeed = 0.2f,
            numberOfScoreToWin = 40,
        ),
        Level(
            numberLevel = 5,
            fieldGameRow = 4,
            fieldGameColumn = 4,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 1,
            bonusFillSpeed = 0.1f,
            numberOfScoreToWin = 50,
        ),
        Level(
            numberLevel = 6,
            fieldGameRow = 4,
            fieldGameColumn = 5,
            additionalBrick = 3,
            numberOfBricksToWin = 3,
            negativeBonusNumber = 2,
            bonusFillSpeed = 0.1f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 7,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 3,
            numberOfBricksToWin = 4,
            negativeBonusNumber = 2,
            bonusFillSpeed = 0.05f,
            numberOfScoreToWin = 80,
        ),
        Level(
            numberLevel = 8,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 2,
            bonusFillSpeed = 0.05f,
            numberOfScoreToWin = 90,
        ),
        Level(
            numberLevel = 9,
            fieldGameRow = 6,
            fieldGameColumn = 7,
            additionalBrick = 4,
            numberOfBricksToWin = 4,
            negativeBonusNumber = 2,
            bonusFillSpeed = 0.02f,
            numberOfScoreToWin = 100,
        ),
        Level(
            numberLevel = 10,
            fieldGameRow = 7,
            fieldGameColumn = 8,
            additionalBrick = 4,
            numberOfBricksToWin = 5,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.02f,
            numberOfScoreToWin = 110,
        ),
        Level(
            numberLevel = 11,
            fieldGameRow = 6,
            fieldGameColumn = 7,
            additionalBrick = 4,
            numberOfBricksToWin = 4,
            negativeBonusNumber = 5,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 110,
        ),
        Level(
            numberLevel = 12,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 3,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.03f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 13,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 4,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 14,
            fieldGameRow = 4,
            fieldGameColumn = 5,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.02f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 15,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 16,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 4,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.02f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 17,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 3,
            negativeBonusNumber = 5,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 18,
            fieldGameRow = 4,
            fieldGameColumn = 5,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.02f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 19,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 5,
            bonusFillSpeed = 0.02f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 20,
            fieldGameRow = 6,
            fieldGameColumn = 7,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 5,
            bonusFillSpeed = 0.02f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 21,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 22,
            fieldGameRow = 4,
            fieldGameColumn = 5,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 23,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 24,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 25,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 26,
            fieldGameRow = 4,
            fieldGameColumn = 5,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 27,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 28,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 29,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 30,
            fieldGameRow = 4,
            fieldGameColumn = 5,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 31,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 32,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 33,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 34,
            fieldGameRow = 4,
            fieldGameColumn = 5,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 35,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 36,
            fieldGameRow = 2,
            fieldGameColumn = 3,
            additionalBrick = 2,
            numberOfBricksToWin = 2,
            negativeBonusNumber = 1,
            bonusFillSpeed = 0.2f,
            numberOfScoreToWin = 20,
        ),
        Level(
            numberLevel = 37,
            fieldGameRow = 3,
            fieldGameColumn = 3,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 2,
            bonusFillSpeed = 0.2f,
            numberOfScoreToWin = 30,
        ),
        Level(
            numberLevel = 38,
            fieldGameRow = 3,
            fieldGameColumn = 4,
            additionalBrick = 3,
            numberOfBricksToWin = 3,
            negativeBonusNumber = 2,
            bonusFillSpeed = 0.1f,
            numberOfScoreToWin = 40,
        ),
        Level(
            numberLevel = 39,
            fieldGameRow = 4,
            fieldGameColumn = 4,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.1f,
            numberOfScoreToWin = 50,
        ),
        Level(
            numberLevel = 40,
            fieldGameRow = 4,
            fieldGameColumn = 5,
            additionalBrick = 3,
            numberOfBricksToWin = 3,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.1f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 41,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 3,
            numberOfBricksToWin = 4,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.05f,
            numberOfScoreToWin = 80,
        ),
        Level(
            numberLevel = 42,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.05f,
            numberOfScoreToWin = 90,
        ),
        Level(
            numberLevel = 43,
            fieldGameRow = 6,
            fieldGameColumn = 7,
            additionalBrick = 4,
            numberOfBricksToWin = 4,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 100,
        ),
        Level(
            numberLevel = 44,
            fieldGameRow = 7,
            fieldGameColumn = 8,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 110,
        ),
        Level(
            numberLevel = 45,
            fieldGameRow = 6,
            fieldGameColumn = 7,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 5,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 110,
        ),
        Level(
            numberLevel = 46,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 47,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 48,
            fieldGameRow = 4,
            fieldGameColumn = 5,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 49,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 50,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 51,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 52,
            fieldGameRow = 4,
            fieldGameColumn = 5,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 53,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 54,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 55,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 56,
            fieldGameRow = 4,
            fieldGameColumn = 5,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 57,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 58,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 59,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 60,
            fieldGameRow = 4,
            fieldGameColumn = 5,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 61,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 62,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 63,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 64,
            fieldGameRow = 4,
            fieldGameColumn = 5,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 65,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 66,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 67,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 68,
            fieldGameRow = 4,
            fieldGameColumn = 5,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 69,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 70,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 71,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 72,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 73,
            fieldGameRow = 4,
            fieldGameColumn = 5,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 74,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 75,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 76,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 3,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        ),
        Level(
            numberLevel = 77,
            fieldGameRow = 4,
            fieldGameColumn = 5,
            additionalBrick = 3,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 60,
        ),
        Level(
            numberLevel = 78,
            fieldGameRow = 5,
            fieldGameColumn = 6,
            additionalBrick = 4,
            numberOfBricksToWin = 0,
            negativeBonusNumber = 4,
            bonusFillSpeed = 0.01f,
            numberOfScoreToWin = 70,
        )
    )
}

data class Level(
    var numberLevel: Int,
    var fieldGameRow: Int,
    var fieldGameColumn: Int,
    var numberOfBricksToWin: Int = 0,

    var numberOfScoreToWin: Int,
    var levelMaxStep: Int = 100,
    var bonusFillSpeed: Float = 0.01F,
    var additionalBrick: Int = 3,
    var negativeBonusNumber: Int = 0,

    var numberLevelPasses: Int = 0,
    var isActive: Boolean = false,
)




